language: objective-c
podfile: Example/Podfile
xcode_workspace: Example/VoiceItApi2IosSDK.xcworkspace
xcode_scheme:  VoiceItApi2IosSDK-Example
osx_image: xcode11.3
xcode_destination: platform=iOS Simulator,OS=13.3,name=iPhone 8 Plus
after_success:
  - ./email.sh
notifications:
  slack:
    secure: uUDpHgP6/6gikJtjPr0FXuLIkor8qAxeWHIVaaTw2wnkIbiLAaP5UmiuTc8eV9zm/4HIJ9FEsWHTyMS7oX1V+NciUfZhNPVDmNC+dg1/uheHxgyMGizGVK5Z2JKioYkR1HFMLxVepfBnEMnE2tDqwnUoamJJDKaKI6EKYIO/7pDIPmGiSCcnNqrV/GjQSvSwXzxK+z8xN3tVFAzDj5AiXIZYuI6tJEfMDHjvnN2d4+97y3ALlm/qxCyZj9gE56ZQdRRuVPc+EX/Nsl2Vhl4uoUOpzdIopH13J8ZE26UK4g4FuZPtVB0m/4qDlvg0SAkdWeh7Gd6yVfdNcr1JBVN5X8vYW9DoWJUaZRZsD9YFhMaaDv299HIxcnzxu6C+b8Q98T7LGhLUzlIgXBteYkRXWg2Lxy7XBswWPsxiIiaS17hsjSEUGfPQgI/X7dRJQ3eWAjIYVdcUQAy4mmcC01z+aUskvzynjTjNfaN9nf8rJD/X2IHO3sc1AsiUOgt7nWLBhxL7Zeaoa2966eUm2swS3QVhpAq4OiEMLOHaNRVOQAFB8u8cJdtoiM+smJWK1wqwjTRgvyqcYtxRcHU0+7CBOIkdiIfFnZgwNtIT3rhWpXA9h3jHOalDQ82wx2dLPcPcE0UwZiHSepipOvqJai0dFnCeXz4I5mZAXr0RDEh38uk=
  email:
    on_success: never
    on_failure: never
